# Generated by Django 5.0.7 on 2024-11-30 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userphoto',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='user_photos/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='date_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='short_epigraphy',
            field=models.TextField(blank=True, null=True),
        ),
    ]
