# Generated by Django 5.0.7 on 2024-11-30 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_userphoto_image_alter_userprofile_date_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='fio',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
