# Generated by Django 5.0.7 on 2024-12-01 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_userphoto_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='ready_for_generating',
            field=models.BooleanField(default=False),
        ),
    ]
