# Generated by Django 5.0.7 on 2024-12-29 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_userprofile_date_joined_userprofile_is_admin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('prompt', models.TextField()),
                ('is_confirmed', models.BooleanField(default=False)),
            ],
        ),
    ]
