# Generated by Django 5.0.7 on 2024-12-31 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_persona'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='current_persona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.persona'),
        ),
    ]
